{% set name = "superstore" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e69c471cf2b584fcb46c404e168f6322a98c79bf6c826ddc6283d6b6a8ceb5ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - faker >=1.0.1
    - pandas >=0.23.4

test:
  imports:
    - superstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timkpaine/superstore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Categorical data generator
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
