{% set name = "superstore" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbc7c60a9ea65def3add748e82c20e481a726df7a26ff60c865cf264f1217e69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - faker >=1.0.1
    - finance-enums >=0.1.0
    - pandas >=0.23.4

test:
  imports:
    - superstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/timkpaine/superstore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Categorical data generator
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
