{% set name = "superstore" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82990d917506c6f122bf98ab48c9c0a8f0b8be4df6cb2bb5f18825a5fbdb05f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - coolname
    - faker >=1.0.1
    - pandas >=0.23.4

test:
  imports:
    - superstore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/timkpaine/superstore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Categorical data generator
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
