{% set name = "superstore" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8292b7e5f915768ebad26b732438422a76b11866c58302076072a2dd4a2b287b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - coolname
    - faker >=1.0.1
    - pandas >=0.23.4

test:
  imports:
    - superstore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/timkpaine/superstore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Categorical data generator
  dev_url: https://github.com/timkpaine/superstore

extra:
  recipe-maintainers:
    - timkpaine
