context:
  name: superstore
  version: "0.3.2"
  python_min: ${{ python_min }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8292b7e5f915768ebad26b732438422a76b11866c58302076072a2dd4a2b287b

build:
  number: 0
  python:
    version_independent: true
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: not (match(python, python_min ~ ".*") and is_abi3)

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - pip
    - hatchling
    - hatch-rs
  run:
    - python
    - pydantic >=2

tests:
  - python:
      imports:
        - superstore
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Categorical data generator
  homepage: https://github.com/1kbgz/superstore
  repository: https://github.com/1kbgz/superstore

extra:
  recipe-maintainers:
    - timkpaine
